[project]
name = "fastapi-django"

[tool.mypy]
mypy_path = [
  "fastapi_django",
]
show_error_codes = true
check_untyped_defs = true

[tool.poetry]
name = "fastapi-django"
version = "0.13.0"
description = ""
authors = ["albertalexandrov <albert-ugatu@list.ru>"]
packages = [{include = "fastapi_django"}]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SergeiVElfimov/fastapi-django"
classifiers = [
    "Natural Language :: English",
    "Framework :: FastAPI",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = ">=0.115.14,<1.0"
prometheus-fastapi-instrumentator = "^7.1.0"
uvicorn = "^0.35.0"
sqlalchemy = "^2.0.41"
alembic = "^1.16.3"
pyjwt = "^2.10.1"
httpx = "^0.28.1"
cryptography = "^45.0.5"
environs = "^14.2.0"
typer = "^0.16.0"
aiosmtplib = "^4.0.1"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.9"
flynt = "^1.0.1"
greenlet = "^3.0.3"
mypy = "^1.10.1"
mypy-extensions = "^1.0.0"
pre-commit = "^3.7.1"
pytest = "^8.2.2"
pytest-asyncio = "^0.23.7"
pytest-cov = "^5.0.0"
tomli = "^2.0.1"
types-click = "^7.1.8"
types-setuptools = "^70.1.0.20240627"
typing-extensions = "^4.12.2"
types-requests = "^2.32.4.20250611"
ruff = "^0.5.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
    ".git",
    ".mypy_cache",
    ".nox",
    ".ruff_cache",
]


[tool.ruff.lint]
select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "SIM",
  "UP",
]
ignore = [
  "A003",  # Argument name should be lowercase.
  "B008",  # Do not perform function calls in argument defaults.
  "D1",  # Missing docstring https://www.pydocstyle.org/en/2.1.1/error_codes.html.
  "D203",  # 1 blank line required before class docstring.
  "D213",  # Multi-line docstring summary should start at the second line.
]

fixable = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "SIM",
  "UP",
]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
known-first-party = [
  "cbr_dws_client",
]
[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
asyncio_mode = "auto"

[project.scripts]
fastapi-django = "fastapi_django.test:main"
